== image:backpack-svgrepo-com.svg[Static,30,pdfwidth=0.3in] Skills


'''

=== savoir-faire

[horizontal]
Leadership:: Accompagnement d'équipes (5 à 15 personnes), mentorat technique, animation d'ateliers DDD
Méthodologies:: DDD (event storming, patterns tactiques), TDD, pair/mob programming, déploiement continu, Kanban, Scrum
Collaboration:: Facilitation d'ateliers métier, alignement technique/produit, amélioration continue

=== stack

[horizontal]
languages:: Java, Typescript, CSS, HTML, XML, JSON, Avro, Yaml, Asciidoc
Technologies::  Kafka, Zookeeper, Schema-registry, Kubernetes, Rancher, Docker, Elasticsearch, Kibana, Logstash, RabbitMQ, Prometheus, Helm, Grafana, Consul
frameworks and libs::  Spring Suite (Springboot, Spring data…), Kafka Streams, Vavr, Jooq, Hibernate, Junit, Liquibase, Gatling, Nest
databases:: Postgres, Oracle, MongoDB
SCM:: Git


=== tools

[horizontal]
IDE:: IntelliJ, Eclipse
OS:: Mac, Linux icon:heart[]
Build:: Maven, Gradle, Github actions, Jenkins, Sonar, Nexus, Rundeck
